<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Performance Dialog Scheduled</title>
</head>
<body style="margin:0;padding:30px;background:#f4f6f9;font-family:Arial,Helvetica,sans-serif;color:#333;">

<table width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center">

            <table width="650" cellspacing="0" cellpadding="0"
                   style="background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #e5e5e5;">

                <tr>
                    <td style="background:#0d6efd;padding:20px 30px;color:white;">
                        <h2 style="margin:0;">Performance Dialog</h2>
                    </td>
                </tr>

                <tr>
                    <td style="padding:30px;">

                        <p style="margin-top:0;">
                            Dear Bapak/Ibu
                            <strong>{{ $employee_name }}</strong>,
                        </p>

                        <p>
                            Performance Dialog Anda telah dijadwalkan oleh atasan Anda.
                        </p>

                        <table width="100%" cellpadding="10"
                               style="border-collapse:collapse;background:#f8f9fa;border:1px solid #e9ecef;margin:25px 0;">

                            <tr>
                                <td width="35%"><strong>Tanggal</strong></td>
                                <td>{{ $date }}</td>
                            </tr>

                            <tr style="background:white;">
                                <td><strong>Waktu</strong></td>
                                <td>{{ $time }}</td>
                            </tr>

                            <tr>
                                <td><strong>Manager</strong></td>
                                <td>{{ $manager_name }}</td>
                            </tr>

                        </table>

                        <p>
                            Silakan hadir sesuai jadwal dan siapkan hal-hal yang ingin didiskusikan.
                        </p>

                        @if(!empty($url))
                            <div style="margin:35px 0;text-align:center;">
                                <a href="{{ $url }}"
                                   style="background:#0d6efd;
                                          color:white;
                                          text-decoration:none;
                                          padding:12px 28px;
                                          border-radius:6px;
                                          display:inline-block;
                                          font-weight:bold;">
                                    View Performance Dialog
                                </a>
                            </div>
                        @endif

                        <p style="margin-top:40px;">
                            Terima kasih.
                        </p>

                    </td>
                </tr>

                <tr>
                    <td style="background:#f8f9fa;
                               text-align:center;
                               padding:18px;
                               color:#888;
                               font-size:12px;">
                        This is an automated email generated by HCIS.<br>
                        Please do not reply to this email.
                    </td>
                </tr>

            </table>

        </td>
    </tr>
</table>

</body>
</html>
